#!/bin/bash

inet=`ifconfig eth0 | grep inet | awk -F: '{print $2}' | awk '{print $1}'`
host=`hostname`

datum=`date +%y%m%d`
time=`date +%H%M%S`

echo $inet
echo $host
echo $datum
echo $time

for i in `seq 1 2`;
do
	/home/pi/netsend/netsend $1 $2 $datum $time $3 $host $inet 
done
